# 2D Numpy in Python

In [4]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

# Convert the list to numpy array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
a=np.random.randn(3,3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.29738909 -0.55650717  0.53806391]
 [ 0.39002774 -0.07016397  0.73189455]
 [-0.17687577 -0.0309531  -0.18624807]]


In [9]:
a = np.random.randn(2, 3) # a.shape = (2, 3)

b = np.random.randn(2, 1) #  b.shape = (2, 1)
c = a + b
print(c)

[[-2.89875008 -0.61878097 -2.7249226 ]
 [-0.05490631 -2.02828651 -1.08813358]]


In [12]:
a=np.random.randn(12288,150) # a.shape = (12288, 150)

b = np.random.randn(150, 45) # b.shape = (150, 45)

c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [6]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)
